export declare type IArgument = {
    [key: string]: any;
};
export declare type IArgTypes = {
    [argument: string]: IArgument;
};
export declare type IArgsUpdater = (args: IArgTypes) => IArgTypes;
export declare const withArgumentType: (name: string, arg: IArgument) => IArgsUpdater;
export declare const withID: () => IArgsUpdater;
export declare const withTestID: () => IArgsUpdater;
export declare const withClassName: () => IArgsUpdater;
export declare const withOnClick: () => IArgsUpdater;
export declare const withOnBlur: () => IArgsUpdater;
export declare const withIsDisabled: () => IArgsUpdater;
export declare const withIsLoading: () => IArgsUpdater;
export declare const withIsSimple: () => IArgsUpdater;
export declare const withChildren: () => IArgsUpdater;
export declare const withVariant: () => IArgsUpdater;
export declare const withSize: () => IArgsUpdater;
export declare const withPosition: (defaultValue?: any, options?: any, controlType?: any) => IArgsUpdater;
export declare const withType: (defaultValue?: any, options?: any, controlType?: any) => IArgsUpdater;
export declare const withIconOnly: () => IArgsUpdater;
export declare const withIcon: (icons?: {
    [key: string]: string;
} | undefined) => IArgsUpdater;
export declare const withBorder: () => IArgsUpdater;
export declare const withBlock: () => IArgsUpdater;
export declare const withFixed: () => IArgsUpdater;
export declare const withColor: () => IArgsUpdater;
export declare const withBackground: () => IArgsUpdater;
export declare const withLeading: () => IArgsUpdater;
export declare const withBold: () => IArgsUpdater;
export declare const withPaddingX: () => IArgsUpdater;
export declare const withPaddingY: () => IArgsUpdater;
export declare const withMarginX: () => IArgsUpdater;
export declare const withMarginY: () => IArgsUpdater;
export declare const withTextAlign: () => IArgsUpdater;
export declare const withShadow: () => IArgsUpdater;
export declare const withIntent: () => IArgsUpdater;
export declare const withAlt: (propName?: string, displayName?: string) => IArgsUpdater;
export declare const withSrc: (propName?: string, displayName?: string) => IArgsUpdater;
export declare const withSrcSet: (propName?: string, displayName?: string) => IArgsUpdater;
export declare const withFluid: () => IArgsUpdater;
export declare const withRatio: () => IArgsUpdater;
export declare const withLazy: () => IArgsUpdater;
export declare const withShowControls: () => IArgsUpdater;
export declare const withCols: () => IArgsUpdater;
export declare const withTitle: () => IArgsUpdater;
export declare const withSubtitle: () => IArgsUpdater;
export declare const withIntro: () => IArgsUpdater;
export declare const withLabel: () => IArgsUpdater;
export declare const withName: () => IArgsUpdater;
export declare const withValue: (type?: string) => IArgsUpdater;
export declare const withChecked: () => IArgsUpdater;
export declare const withSingleItem: () => IArgsUpdater;
export declare const withOnChange: () => IArgsUpdater;
export declare const withGeneralArgTypes: () => IArgsUpdater[];
export declare const withMargin: () => IArgsUpdater[];
export declare const withPadding: () => IArgsUpdater[];
export declare const withMarginPadding: () => IArgsUpdater[];
export declare const withBox: () => (IArgsUpdater | IArgsUpdater[])[];
export declare const withImage: (propPrefix?: string | undefined, hasSourceSet?: boolean | undefined) => IArgsUpdater[];
export declare const withCard: () => IArgsUpdater[];
export declare const withOnClose: () => IArgsUpdater;
