declare const _default: {
    arrow: string;
    arrowdown: string;
    arrowl: string;
    arrowup: string;
    cart: string;
    check: string;
    close: string;
    copy: string;
    download: string;
    edit: string;
    filter: string;
    globe: string;
    hidden: string;
    locked: string;
    minus: string;
    pin: string;
    plus: string;
    search: string;
    shared: string;
    show: string;
    shutdown: string;
    sortable: string;
    sortdown: string;
    sortup: string;
    trash: string;
    user: string;
    question: string;
    resize: string;
    compressed: string;
    normal: string;
};
export default _default;
